fix: have crt* located by dlopen and make repo a flake
snowball-lang/snowball pull request #156
Opened 2023-12-13 03:26 UTC by Perigord-Kleisli

2023-12-13 15:50 UTC, mauro-balades requested changes

2023-12-13 15:50 UTC, mauro-balades commented on src/builder/linker/linux/ld.cc
> +        Syntax::E<LINKER_ERR>("crtn.o was loaded as a shared library");
did you mean `wasn't`?

2023-12-13 15:50 UTC, mauro-balades commented on flake.nix
> +          libxml2
xml?

2023-12-13 15:50 UTC, mauro-balades commented on flake.nix
> +        version = "0.0.8";
can't we import this version from [snowball.version.str](https://github.com/snowball-lang/snowball/blob/dev/snowball.version.str)?

2023-12-13 15:57 UTC, mauro-balades commented on flake.lock
Shoudn't we remove this file?

2023-12-13 15:58 UTC, mauro-balades commented
Can you give me push access to your repo so I can fix a small issue?

2023-12-14 06:33 UTC, emm312 commented
LGTM

2023-12-14 06:34 UTC, emm312 commented on flake.lock
i dont think you should

2023-12-14 06:38 UTC, mauro-balades commented
> LGTM

There are still pending changes

2023-12-14 06:40 UTC, emm312 commented
> > LGTM
> 
> There are still pending changes

i meant the code looked good

2023-12-14 06:44 UTC, Perigord-Kleisli commented on src/builder/linker/linux/ld.cc
> +        Syntax::E<LINKER_ERR>("crtn.o was loaded as a shared library");
Was, since it should be loaded like a static library. It probably won't happen but this code is just here in case someone has `crtn.o` as a shared library for some reason

2023-12-14 06:49 UTC, mauro-balades commented
True
~ mauro




14 Dec 2023, 07:40 by ***@***.***:

>
>
>
>
>>>
>>> LGTM
>>>
>>>
>>
>> There are still pending changes
>>
>>
>
> i meant the code looked good
>
>
>
> —
> Reply to this email directly, > view it on GitHub <https://github.com/snowball-lang/snowball/pull/156#issuecomment-1855234651>> , or > unsubscribe <https://github.com/notifications/unsubscribe-auth/AVWNLZVBFDA3NMSAYUWIJWLYJKNM7AVCNFSM6AAAAABASPC4ZCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJVGIZTINRVGE>> .
> You are receiving this because you were assigned.> Message ID: > <snowball-lang/snowball/pull/156/c1855234651> @> github> .> com>
>
>
>

2023-12-14 06:50 UTC, mauro-balades commented on src/builder/linker/linux/ld.cc
> +        Syntax::E<LINKER_ERR>("crtn.o was loaded as a shared library");
I see what you did there, nice.

2023-12-17 00:35 UTC, merged

2023-12-17 00:41 UTC, mauro-balades commented
it does work! 🥳

2023-12-17 00:42 UTC, mauro-balades commented
I still don't know why XML is required though...