add a JIT
snowball-lang/snowball pull request #40
Opened 2023-07-04 17:22 UTC by emm312

2023-07-04 18:50 UTC, mauro-balades commented
https://github.com/snowball-lang/snowball/pull/40/commits/d0393efc27c592014edaa20150180fbb600bd744#diff-63334f106abfc4439100cf86cd2b83bdbf88bf4a6b101f176ec26bad6d3ce328L2

File not found, fix this relative include

2023-07-19 17:40 UTC, mauro-balades requested changes
just some small changes. Didn't you send me that it segfaulted or smth? It needs to load runtime and other shared libs, idk how we could implement that, ill look into it.

2023-07-19 17:40 UTC, mauro-balades commented on app/commands/run.h
> +    DUMP(p_opts.jit);
remove this before merge, thanks

2023-07-19 17:40 UTC, mauro-balades commented on src/constants.h
> +#define _SNOWBALL_BYTECODE_DEBUG 0
change it back to `1`

2023-07-20 05:58 UTC, emm312 commented on build_scripts/dbg.sh
> +cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug \
ninja doesn’t colour the errors

2023-07-20 05:58 UTC, emm312 commented on app/commands/run.h
> +        return 0;
you marked it as void in an example

2023-07-20 05:58 UTC, emm312 commented on app/commands/run.h
> +    DUMP(p_opts.jit);
ok

2023-07-20 05:58 UTC, emm312 commented on src/constants.h
> +#define _SNOWBALL_BYTECODE_DEBUG 0
no

2023-07-20 09:48 UTC, mauro-balades commented on app/commands/run.h
> +        return 0;
It's OK, u can change it

2023-07-21 07:53 UTC, closed without merging